---

- name: install centos software collections
  package:
    name: centos-release-scl-rh
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: collections_enabled|bool and ansible_distribution == 'CentOS'
  tags:
    - git
    - base_git

- name: enable rhel software collections
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when: collections_enabled|bool and ansible_distribution == 'RedHat'
  tags:
    - git
    - base_git

- name: Set git
  set_fact:
    base_git: rh-git29
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 6
  tags:
    - git
    - base_git

- name: Set git
  set_fact:
    base_git: rh-git218
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7
  tags:
    - git
    - base_git

- name: Set git packages
  when: collections_enabled|bool and ansible_os_family == 'RedHat'
  set_fact:
    base_git_rpms:
      - "{{ base_git }}"
      - "{{ base_git }}-git-svn"
      - "{{ base_git }}-perl-Git-SVN"
      - "{{ base_git }}-git-cvs"
      - "{{ base_git }}-git-p4"
  tags:
    - git
    - base_git

- name: Install Git software collection
  become: yes
  when: collections_enabled|bool and ansible_os_family == 'RedHat'
  yum:
    name: "{{ base_git_rpms }}"
    state: present
    update_cache: yes
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  tags:
    - git
    - base_git

- name: Enable Git software collection
  file:
    src: "/opt/rh/{{ base_git }}/enable"
    path: /etc/profile.d/rh-git.sh
    state: link
  when: collections_enabled|bool and ansible_os_family == 'RedHat'
  tags:
    - git
    - base_git

- name: Disable Git software collection
  file:
    path: /etc/profile.d/rh-git.sh
    state: absent
  when: not collections_enabled|bool and ansible_os_family == 'RedHat'
  tags:
    - git

- name: Disable Git software collection
  file:
    path: /etc/profile.d/rh-git.sh
    state: absent
  when: not collections_enabled|bool and ansible_os_family == 'RedHat'
  tags:
    - git

- name: Install Git from yum repo
  become: yes
  when: not collections_enabled|bool and ansible_os_family == 'RedHat'
  yum:
    name: git
    state: present
    update_cache: yes
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  tags:
    - git
    - base_git

- name: Install Git from apt repo
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: git
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  tags:
    - git
    - base_git

- name: Disable Git software collection
  file:
    src: "/opt/rh/{{ base_git }}/enable"
    path: /etc/profile.d/rh-git.sh
    state: absent
  when: not collections_enabled|bool and ansible_os_family == 'RedHat'
  tags:
    - git
    - base_git
