---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-git-centos6
    image: centos:6
    privileged: true
  - name: base-git-centos7
    image: milcom/centos7-systemd
    privileged: true
  - name: base-git-ubuntu
    image: ubuntu
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      stdout_callback: yaml
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
